server:
  port: 8090

spring:
  application:
    name: msvc-student

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL_STUDENT}
    username: ${USERNAME_STUDENT}
    password: ${PASSWORD_STUDENT}

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka