server:
  port: 9090

spring:
  application:
    name: msvc-course

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URLCOURSE}
    username: ${USERNAMECOURSE}
    password: ${PASSWORDCOURSE}

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
